# Generated by Django 4.2.6 on 2023-11-28 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('tipo_tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('S1', 'Suspensión de actividades'), ('S2', 'Suspensión de actividades PM'), ('P', 'Periodo Lectivo')], default='F', max_length=10)),
                ('tipo_segmento', models.CharField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrera')], default='C', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_segmento', models.CharField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrera')], default='C', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
