# Generated by Django 4.2.6 on 2023-11-28 08:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nuestrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_segmento',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrera')], max_length=10),
        ),
    ]
